steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/cs-admin-bot-497509/cs-improvement-bot:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/cs-admin-bot-497509/cs-improvement-bot:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cs-improvement-bot'
      - '--image'
      - 'gcr.io/cs-admin-bot-497509/cs-improvement-bot:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--timeout'
      - '3600'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--update-secrets=SLACK_BOT_TOKEN=SLACK_BOT_TOKEN:latest,SLACK_SIGNING_SECRET=SLACK_SIGNING_SECRET:latest,SLACK_APP_TOKEN=SLACK_APP_TOKEN:latest,SLACK_CHANNEL_ID=SLACK_CHANNEL_ID:latest,SLACK_CHANNEL_NAME=SLACK_CHANNEL_NAME:latest,JIRA_SERVER_URL=JIRA_SERVER_URL:latest,JIRA_USER_EMAIL=JIRA_USER_EMAIL:latest,JIRA_API_TOKEN=JIRA_API_TOKEN:latest,CHARGEBEE_API_KEY=CHARGEBEE_API_KEY:latest'
      - '--min-instances=1'
      - '--no-cpu-throttling'

images:
  - 'gcr.io/cs-admin-bot-497509/cs-improvement-bot:latest'

options:
  logging: CLOUD_LOGGING_ONLY
